name: CI and Preview

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  deployments: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          check-latest: true

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: |
            - recursive: true
              args: [--no-frozen-lockfile]

      - name: lint
        run: pnpm lint

      - name: Build with Next.js
        run: pnpm build
