name: CI and Preview

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  deployments: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          check-latest: true

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: |
            - recursive: true
              args: [--no-frozen-lockfile]

      - name: Prepare build
        env:
          VITE_SUPABASE_URL: ${{ vars.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
        run: |
          touch .env.local
          echo "VITE_SUPABASE_URL=${VITE_SUPABASE_URL}" >> .env.local
          echo "VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}" >> .env.local

      - name: lint
        run: pnpm lint

      - name: Build with Next.js
        run: pnpm build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 189f193d40c08d2618ee4b94de81d79e
          projectName: ${{ github.event.repository.name }}
          directory: ./dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: preview
          workingDirectory: ./
          wranglerVersion: '3'
